services:
  gocast-voice-service:
    image: ghcr.io/tum-dev/gocast-voice-service:0.2.0
    volumes:
      - /tmp/whisper:/tmp/whisper
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    ports:
      - "50051:50051"
    command:
      - "-queue-size"
      - "10000"
      - "-target"
      - "131.159.2.73:50053"